apiVersion: apps/v1
kind: Deployment
metadata:
    name: team-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: team-service
template:
    metadata:
        labels:
            app: team-service
    spec:
    containers:
        - name: team-service
          image: my-registry/team-service:latest
          resources:
            limits:
                memory: 1Gi
                cpu: 1 
            requests:
                memory: 800Mi
                cpu: 500m
          ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
    name: team-service
spec:
    selector:
        app: team-service
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
           
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: team-service
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
                name: team-service
                port:
                    number: 80

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: team-service
spec:
  podSelector:
    matchLabels:
      app: team-service
  policyTypes:  
    Egress
  egress:
    - to:
        - podSelector:
            -matchLabels:
                app: 
                - match-service
                  player-service
                  stats-service
      ports:
        - protocol: TCP
          port: 8080                 





